### ISSUE TITLE
Zapomiane hasło

### ISSUE THREAD

**Issue by jakub-zulewski** [jakub-zulewski/Zakaria#34]
- [x] Ostylować stronę /forgotpassword (email form)
- [x] Ostylować stronę /changeforgotpassword (formularz po otrzymaniu linku do zmiany hasła)
- [x] Ostylować stronę /activateemail (po kliknięciu na link aktywacyjny nowego maila)

**Comment by RobertCiechowski** [comment]
Ostylowane.
